version: 2
updates:
- package-ecosystem: docker
  directory: "/5.1.0-bionic"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/5.0.0-xenial"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/5.1.0-xenial"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
